deploytype: k8s

local_values:
  image_dir: /tele_data_share/public/upload_image

  MAIN_NODE_IP: 10.127.20.218

  image_uploader_script:
    read_from_file: template/image_uploader.py
    map: "'\\n    '.join(content.split('\\n'))"
  image_uploader_yml:
    read_from_file: template/apply.yml

secret:
  # - seaweed_s3id

prepare:
  - pip_base:
  - filemap:
      content: ${image_uploader_yml}
      path: image_uploader/apply.yml
      mode: 755

  - image: python:3.12.5
  - image: nginx:1.27
  - image: busybox:1.36.1

k8s:
  image_uploader:
    k8s-dir: prepare/image_uploader
