deploytype: bin

local_values:
  main_node_ip: "10.127.20.218"

prepare:
  - packer: https://github.com/ActivePeter/offline_installer_packer/releases/download/libxcb
  # - url: https://rpmfind.net/linux/almalinux/8.10/BaseOS/aarch64/os/Packages/elfutils-libelf-devel-0.190-2.el8.aarch64.rpm
  #   as: elfutils-libelf-devel_arm64.rpm

  # - url: https://rpmfind.net/linux/almalinux/8.10/BaseOS/x86_64/os/Packages/elfutils-libelf-devel-0.190-2.el8.x86_64.rpm
  #   as: elfutils-libelf-devel_amd64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/aarch64/os/Packages/cmake-3.26.5-2.el8.aarch64.rpm
  #   as: cmake_arm64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/cmake-3.26.5-2.el8.x86_64.rpm
  #   as: cmake_amd64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/aarch64/os/Packages/gcc-8.5.0-22.el8_10.aarch64.rpm
  #   as: gcc_arm64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/gcc-8.5.0-22.el8_10.x86_64.rpm
  #   as: gcc_amd64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/gcc-c++-8.5.0-22.el8_10.x86_64.rpm
  #   as: gcc_cxx_amd64.rpm

  # - url: https://repo.almalinux.org/almalinux/8/AppStream/aarch64/os/Packages/gcc-c++-8.5.0-22.el8_10.aarch64.rpm
  #   as: gcc_cxx_arm64.rpm
  # # zlib
  # # - url: http://launchpadlibrarian.net/193821327/yum_3.4.3-3_all.deb
  # #   as: yum_amd64.deb

  # # - url: http://launchpadlibrarian.net/193821327/yum_3.4.3-3_all.deb
  # #   as: yum_arm64.deb

  # - filemap:
  #     path: install.py
  #     content: |
  #       import os
  #       import sys
  #       import urllib.request

  #       try:
  #           os.mkdir("/tmp/install_yum")
  #       except:
  #           pass
  #       os.chdir("/tmp/install_yum")
  #       urllib.request.urlretrieve("http://${main_node_ip}:8003/bin_yum/yum.zip", "/tmp/install_yum/yum.zip")
  #       ARCH=""
  #       if os.uname().machine == "aarch64":
  #           ARCH="arm64"
  #       if os.uname().machine == "x86_64":
  #           ARCH="amd64"
  #       if os.uname().machine == "arm64":
  #           ARCH="arm64"

  #       files=[
  #           f"libssl1_1_{ARCH}.deb",
  #           f"openssl_{ARCH}.deb",
  #           f"libpython2.7-minimal_{ARCH}.deb",
  #           f"python2.7-minimal_{ARCH}.deb",
  #           f"mime-support_{ARCH}.deb",
  #           f"libpython2.7-stdlib_{ARCH}.deb",
  #           f"python2.7_{ARCH}.deb",
  #           f"libpopt0_{ARCH}.deb",
  #           f"libelf1_{ARCH}.deb",
  #           f"libgdbm5_{ARCH}.deb",
  #           f"perl-modules_{ARCH}.deb",
  #           f"libperl5_26_{ARCH}.deb",
  #           f"perl-base_{ARCH}.deb",
  #           f"perl_{ARCH}.deb",
  #           f"libnspr4_{ARCH}.deb",
  #           f"libnss3_{ARCH}.deb",
  #           f"liblua5_2_{ARCH}.deb",
  #           f"librpmio8_{ARCH}.deb",
  #           f"librpm8_{ARCH}.deb",
  #           f"librpmbuild8_{ARCH}.deb",
  #           f"debugedit_{ARCH}.deb",
  #           f"librpmsign8_{ARCH}.deb",
  #           f"rpm2cpio_{ARCH}.deb",
  #           f"rpm-common_{ARCH}.deb",
  #           f"rpm_{ARCH}.deb",
  #           f"python-rpm_{ARCH}.deb",
  #           f"python-urlgrabber_all.deb",
  #           f"python-pycurl_{ARCH}.deb",
  #           f"python-sqlitecachec_{ARCH}.deb"
  #       ]

  #       for f in files:
  #           print(f"downloading {f}")
  #           urllib.request.urlretrieve(f"http://${main_node_ip}:8003/bin_yum/{f}", f"/tmp/install_yum/{f}")
  #           os.system(f"dpkg -i {f}")

  #       os.system("unzip -o yum.zip")
  #       os.system("chmod -R 755 ./")
  #       os.system("cp -r etc /")
  #       os.system("cp -r usr /")
  #       os.system("cp -r var /")
  #       if not os.path.exists("/usr/bin/python"):
  #           os.system("ln -s /usr/bin/python2.7 /usr/bin/python")
  #       script = urllib.request.urlopen("http://10.127.20.218:8003/bin_easy_config/set_rpm_source.py").read()
  #       exec(script)
  #     mode: 755

bin:
  libxcb:
    no_default_installer:
    # apt:
    #   yum:
