apiVersion: v1
kind: Service
metadata:
  name: s3-server-service
  namespace: tele-deployment
spec:
  type: NodePort
  selector:
    app: s3-server
  ports:
    - protocol: TCP
      port: 8014
      targetPort: 8014
      nodePort: 31014 # 可选，指定NodePort范围内的端口号
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-server
  namespace: tele-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-server
  template:
    metadata:
      labels:
        app: s3-server
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0

      containers:
        - name: s3-server
          image: harbor.telecom-ai.com.cn/teleinfra/python:3.12.5
          command: ["bash", "-c"]
          args:
            - |
              echo "setting up pip source"
              # .urlretrieve(url, deb)
              python3 -c 'import urllib.request, os; urllib.request.urlretrieve("http://10.127.20.218:8003/bin_s3_server/s3-server",s3-server);' | python3

              echo "installing pyyaml"
              pip3 install pyyaml requests

              chown $(whoami) s3-server

              ./s3-server --host 0.0.0.0 --fs-root /share_mount

              sleep inf
          volumeMounts:
            - name: damoxing
              mountPath: /share_mount/damoxing
            - name: damoxing1
              mountPath: /share_mount/damoxing1

      volumes:
        - name: damoxing
          hostPath:
            path: /damoxing
        - name: damoxing1
          hostPath:
            path: /damoxing1
      # - name: env-exporter-volume
      #   emptyDir: {}
      # - name: juice-s3-policy-conf
      #   secret:
      #     secretName: tele-deploy-secret
      #     items:
      #       - key: juice_s3_policy_conf
      #         path: juice.yml
      # - name: jfs-sftp-persist
      #   hostPath:
      #     path: ${share_root}/kube-system-data/jfs-sftp
      #     type: DirectoryOrCreate
