deploytype: k8s

local_values:
  # DEFAULT_DEPLOY_DIR: /juice_seaweed

secret:
  # - seaweed_s3id
  # - seaweed_s3pw

prepare:
  - image: quay.io/tigera/operator:v1.29.6
  - image: calico/typha:v3.25.2
  - image: calico/kube-controllers:v3.25.2
  - image: calico/apiserver:v3.25.2
  - image: calico/cni:v3.25.2
  - image: calico/node-driver-registrar:v3.25.2
  - image: calico/csi:v3.25.2
  - image: calico/pod2daemon-flexvol:v3.25.2
  - image: calico/node:v3.25.2
