deploytype: bin

prepare:
  # x86
  - url: https://github.com/ActivePeter/bin_repo_0/releases/download/bottom0.10.2/btm_amd64
    # trans: "unzip -o rclone-v1.68.0-linux-amd64.zip && cp rclone-v1.68.0-linux-amd64/rclone rclone_amd64"
  # arm
  - url: https://github.com/ClementTsang/bottom/releases/download/0.10.2/bottom_aarch64-unknown-linux-gnu.tar.gz
    trans: "tar -zxvf bottom_aarch64-unknown-linux-gnu.tar.gz && mv btm btm_arm64 && rm -rf completion"
bin:
  btm:
