apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "dcgm-exporter"
  namespace: monitoring
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
    app.kubernetes.io/version: "3.6.0"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
      app.kubernetes.io/version: "3.6.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "dcgm-exporter"
        app.kubernetes.io/version: "3.6.0"
      name: "dcgm-exporter"
    spec:
      hostNetwork: true
      containers:
        - image: "harbor.telecom-ai.com.cn/teleinfra/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04"
          env:
            - name: "DCGM_EXPORTER_LISTEN"
              value: ":9404"
            - name: "DCGM_EXPORTER_KUBERNETES"
              value: "true"
          name: "dcgm-exporter"
          ports:
            - name: "metrics"
              containerPort: 9404
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: "pod-gpu-resources"
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
        - name: "pod-gpu-resources"
          hostPath:
            path: "/var/lib/kubelet/pod-resources"
