apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    type: prometheus-hostpath-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/tele_data_share/kube-system-data/prometheus" 
    type: DirectoryOrCreate