apiVersion: v1
kind: Service
metadata:
  name: jfs-samba-service
  namespace: tele-deployment
spec:
  type: NodePort
  selector:
    app: jfs-samba
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
      nodePort: 31445 # 可选，指定NodePort范围内的端口号
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfs-samba
  namespace: tele-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfs-samba
  template:
    metadata:
      labels:
        app: jfs-samba
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
        - name: format-configs
          image: harbor.telecom-ai.com.cn/teleinfra/python:3.12.5
          command: ["bash", "-c"]
          args:
            - |
              echo "setting up pip source"
              python3 -c 'import urllib.request, os; script = urllib.request.urlopen("http://10.127.20.218:8003/bin_easy_config/set_pip_source.py").read(); print(script.decode())' | python3

              echo "installing pyyaml"
              pip3 install pyyaml

              echo "transforming juice.yml to env exporter"
              echo "${prepare_entry}" > _prepare_entry.py
              python3 -c "import base64; open('prepare_entry.py', 'w').write(base64.b64decode(open('_prepare_entry.py', 'r').read().strip()).decode('utf-8'))"

              python3 prepare_entry.py
          volumeMounts:
            - name: storage-policy-conf
              mountPath: /app/s3_conf
            - name: env-exporter-volume
              mountPath: /app/prepare_entry
      containers:
        - name: jfs-samba
          image: harbor.telecom-ai.com.cn/teleinfra/samba:latest
          ports:
            - containerPort: 445
          command: ["/bin/sh", "-c"]
          args:
            # export LD_LIBRARY_PATH=/host_lib64:/host_lib:$LD_LIBRARY_PATH;
            - |
              /bin/sh /app/prepare_entry/entry.sh
          volumeMounts:
            # - name: share-root
            #   mountPath: /share
            - name: env-exporter-volume
              mountPath: /app/prepare_entry
            - name: damoxing
              mountPath: /share/damoxing
            - name: damoxing1
              mountPath: /share/damoxing1

      volumes:
        - name: damoxing
          hostPath:
            path: /damoxing
        - name: damoxing1
          hostPath:
            path: /damoxing1
        # - name: share-root
        #   hostPath:
        #     path: ${share_root}
        - name: storage-policy-conf
          secret:
            secretName: tele-deploy-secret
            items:
              - key: storage_policy_conf
                path: storage.yml
        - name: env-exporter-volume
          emptyDir: {}
