apiVersion: v1
kind: Service
metadata:
  name: jfs-sftp-service
  namespace: tele-deployment
spec:
  type: NodePort
  selector:
    app: jfs-sftp
  ports:
    - protocol: TCP
      port: 2022
      targetPort: 2022
      nodePort: 31022 # 可选，指定NodePort范围内的端口号
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfs-sftp
  namespace: tele-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfs-sftp
  template:
    metadata:
      labels:
        app: jfs-sftp
    spec:
      nodeSelector:
        kubernetes.io/hostname: sh-a523-4090gpu-120
      hostNetwork: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0

      containers:
        - name: jfs-sftp
          image: harbor.telecom-ai.com.cn/teleinfra/sftpgo:v2.6.2
          ports:
            - containerPort: 2022
          command: ["/bin/sh", "-c"]
          env:
            - name: SFTPGO_DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tele-deploy-secret
                  key: DEFAULT_ADMIN_USERNAME
            - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tele-deploy-secret
                  key: DEFAULT_ADMIN_PASSWORD
          args:
            - |
              FILE_TO_WATCH="/app/prepare_entry/init.sh"
              while [ ! -f "$FILE_TO_WATCH" ]; do
                echo "Waiting for file $FILE_TO_WATCH to appear..."
                sleep 1
              done
              bash /app/prepare_entry/init.sh
              sed -i 's/"create_default_admin": false,/"create_default_admin": true,/g' /etc/sftpgo/sftpgo.json
              sftpgo serve
          volumeMounts:
            - name: share-root
              mountPath: /share
            - name: env-exporter-volume
              mountPath: /app/prepare_entry
            - name: jfs-sftp-persist
              mountPath: /srv/sftpgo

        - name: init-gosftp
          image: harbor.telecom-ai.com.cn/teleinfra/python:3.12.5
          command: ["bash", "-c"]
          env:
            - name: SFTPGO_DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tele-deploy-secret
                  key: DEFAULT_ADMIN_USERNAME
            - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tele-deploy-secret
                  key: DEFAULT_ADMIN_PASSWORD
          args:
            - |
              echo "setting up pip source"
              python3 -c 'import urllib.request, os; script = urllib.request.urlopen("http://10.127.20.218:8003/bin_easy_config/set_pip_source.py").read(); print(script.decode())' | python3

              echo "installing pyyaml"
              pip3 install pyyaml requests

              echo "transforming juice.yml to env exporter"
              echo "${prepare_entry}" > _prepare_entry.py
              python3 -c "import base64; open('prepare_entry.py', 'w').write(base64.b64decode(open('_prepare_entry.py', 'r').read().strip()).decode('utf-8'))"

              python3 prepare_entry.py

              sleep inf
          volumeMounts:
            - name: share-root
              mountPath: /share
            - name: env-exporter-volume
              mountPath: /app/prepare_entry
            - name: juice-s3-policy-conf
              mountPath: /app/s3_conf

      volumes:
        - name: share-root
          hostPath:
            path: ${share_root}
        - name: env-exporter-volume
          emptyDir: {}
        - name: juice-s3-policy-conf
          secret:
            secretName: tele-deploy-secret
            items:
              - key: juice_s3_policy_conf
                path: juice.yml
        - name: jfs-sftp-persist
          hostPath:
            path: ${share_root}/kube-system-data/jfs-sftp
            type: DirectoryOrCreate
