apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: grafana-hostpath-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/tele_data_share/kube-system-data/grafana"
    type: DirectoryOrCreate