deploytype: k8s

nodes: nodes_jd.yml

local_values: []
#   share_root: /tele_data_share
#   prepare_entry:
#     read_from_file: template/prepare_entry.py
#     map: "__import__('base64').b64encode(content.encode()).decode()"
#   apply:
#     read_from_file: template/apply.yml

prepare:
  # - image: drakkan/sftpgo:v2.6.2
  # - filemap:
  #     content: ${apply}
  #     path: jfs-sftp/apply.yml
  #     mode: 755
  # - url: https://github.com/winfsp/sshfs-win/releases/download/v3.5.20357/sshfs-win-3.5.20357-x64.msi

k8s:
  s3-server-k8s:
    k8s-dir: prepare/s3-server-k8s
