apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepi
  template:
    metadata:
      labels:
        app: kubepi
    spec:
      containers:
        - name: kubepi
          image: harbor.telecom-ai.com.cn/teleinfra/kubepi:v1.8.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubepi-service
spec:
  selector:
    app: kubepi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
